name: foodepie
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  http: ^0.12.1
  url_launcher: ^5.4.5
  flare_flutter: ^2.0.3
  curved_navigation_bar: ^0.3.2
  webview_flutter: ^0.3.21
  modal_progress_hud: ^0.1.3
  expandable: ^4.1.4
  chips_choice: ^1.2.0
  percent_indicator: ^2.1.4
  flutter_holo_date_picker: ^0.1.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  assets:
  - images/
  - login_teddy/

  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf



